import { mkdir, readFile, writeFile } from "node:fs/promises";
import { posix, resolve } from "node:path";
import solc from "solc";
import "./compile-child-validation-probe.mjs";

const root = resolve(import.meta.dirname, "..");
const sourceFiles = [
  "src/StarRegistry.sol",
  "src/StarEnsRegistrar.sol",
  "src/StarToken.sol",
  "src/StarGoals.sol",
  "src/StarFamilyVault.sol",
  "src/StarFamilyVaultFactory.sol",
  "src/StarChildAccountFactory.sol",
  "src/interfaces/IAqua.sol",
  "src/interfaces/IStarRegistry.sol",
  "src/interfaces/IStarToken.sol",
  "@1inch/aqua/src/Aqua.sol",
  "vendor/1inch-swap-vm/src/routers/AquaSwapVMRouter.sol",
];
const sources = {};
const pendingSources = [...sourceFiles];
while (pendingSources.length > 0) {
  const sourceName = pendingSources.pop();
  if (sources[sourceName]) continue;
  const sourcePath = sourceName.startsWith("@1inch/aqua/")
    ? resolve(
        root,
        "vendor/1inch-aqua",
        sourceName.slice("@1inch/aqua/".length),
      )
    : sourceName.startsWith("@")
      ? resolve(root, "node_modules", sourceName)
      : resolve(root, sourceName);
  const content = await readFile(sourcePath, "utf8");
  sources[sourceName] = { content };

  for (const match of content.matchAll(
    /import\s+(?:[^"']*?\s+from\s+)?["']([^"']+)["']\s*;/g,
  )) {
    const imported = match[1];
    const normalized = imported.startsWith("@")
      ? imported
      : posix.normalize(posix.join(posix.dirname(sourceName), imported));
    if (!sources[normalized]) pendingSources.push(normalized);
  }
}

const input = {
  language: "Solidity",
  sources,
  settings: {
    optimizer: { enabled: true, runs: 500 },
    viaIR: true,
    evmVersion: "cancun",
    outputSelection: {
      "*": {
        "*": [
          "abi",
          "evm.bytecode.object",
          "evm.deployedBytecode.object",
          "evm.deployedBytecode.immutableReferences",
        ],
      },
    },
  },
};

const output = JSON.parse(solc.compile(JSON.stringify(input)));

const errors = (output.errors ?? []).filter(
  (item) => item.severity === "error",
);
if (errors.length) {
  for (const error of output.errors) console.error(error.formattedMessage);
  process.exit(1);
}

await mkdir(resolve(root, "artifacts"), { recursive: true });
await writeFile(
  resolve(root, "artifacts", "standard-json-input.json"),
  `${JSON.stringify(input, null, 2)}\n`,
);
for (const [sourceName, contracts] of Object.entries(output.contracts)) {
  for (const [contractName, contract] of Object.entries(contracts)) {
    if (
      !sourceName.startsWith("src/") &&
      !["Aqua", "AquaSwapVMRouter"].includes(contractName)
    )
      continue;
    const artifact = {
      contractName,
      sourceName,
      compilerVersion: solc.version(),
      optimizer: input.settings.optimizer,
      viaIR: input.settings.viaIR,
      evmVersion: input.settings.evmVersion,
      abi: contract.abi,
      bytecode: `0x${contract.evm.bytecode.object}`,
      deployedBytecode: `0x${contract.evm.deployedBytecode.object}`,
      immutableReferences:
        contract.evm.deployedBytecode.immutableReferences ?? {},
    };
    await writeFile(
      resolve(root, "artifacts", `${contractName}.json`),
      `${JSON.stringify(artifact, null, 2)}\n`,
    );
  }
}

const registryAbi = output.contracts["src/StarRegistry.sol"].StarRegistry.abi;
const ensRegistrarAbi =
  output.contracts["src/StarEnsRegistrar.sol"].StarEnsRegistrar.abi;
const starTokenAbi = output.contracts["src/StarToken.sol"].StarToken.abi;
const starGoalsAbi = output.contracts["src/StarGoals.sol"].StarGoals.abi;
const questsAbi = output.contracts["src/StarQuests.sol"].StarQuests.abi;
const familyVaultAbi =
  output.contracts["src/StarFamilyVault.sol"].StarFamilyVault.abi;
const familyVaultFactoryAbi =
  output.contracts["src/StarFamilyVaultFactory.sol"].StarFamilyVaultFactory.abi;
const childAccountAbi =
  output.contracts["src/StarChildAccount.sol"].StarChildAccount.abi;
const childAccountFactoryAbi =
  output.contracts["src/StarChildAccountFactory.sol"].StarChildAccountFactory
    .abi;
const protocolEventsAbi = [
  ...registryAbi,
  ...starTokenAbi,
  ...starGoalsAbi,
  ...questsAbi,
  ...familyVaultAbi,
  ...familyVaultFactoryAbi,
].filter((item) => item.type === "event");
await mkdir(resolve(root, "abi"), { recursive: true });
await writeFile(
  resolve(root, "abi/index.js"),
  [
    "// Generated by scripts/compile.mjs. Do not edit by hand.",
    `export const registryAbi = ${JSON.stringify(registryAbi, null, 2)};`,
    `export const ensRegistrarAbi = ${JSON.stringify(ensRegistrarAbi, null, 2)};`,
    `export const starTokenAbi = ${JSON.stringify(starTokenAbi, null, 2)};`,
    `export const starGoalsAbi = ${JSON.stringify(starGoalsAbi, null, 2)};`,
    `export const questsAbi = ${JSON.stringify(questsAbi, null, 2)};`,
    `export const familyVaultAbi = ${JSON.stringify(familyVaultAbi, null, 2)};`,
    `export const familyVaultFactoryAbi = ${JSON.stringify(familyVaultFactoryAbi, null, 2)};`,
    `export const childAccountAbi = ${JSON.stringify(childAccountAbi, null, 2)};`,
    `export const childAccountFactoryAbi = ${JSON.stringify(childAccountFactoryAbi, null, 2)};`,
    `export const protocolEventsAbi = ${JSON.stringify(protocolEventsAbi, null, 2)};`,
    "",
  ].join("\n"),
);
await writeFile(
  resolve(root, "abi/index.d.ts"),
  [
    "// Generated by scripts/compile.mjs. Do not edit by hand.",
    `export declare const registryAbi: readonly ${JSON.stringify(registryAbi, null, 2)};`,
    `export declare const ensRegistrarAbi: readonly ${JSON.stringify(ensRegistrarAbi, null, 2)};`,
    `export declare const starTokenAbi: readonly ${JSON.stringify(starTokenAbi, null, 2)};`,
    `export declare const starGoalsAbi: readonly ${JSON.stringify(starGoalsAbi, null, 2)};`,
    `export declare const questsAbi: readonly ${JSON.stringify(questsAbi, null, 2)};`,
    `export declare const familyVaultAbi: readonly ${JSON.stringify(familyVaultAbi, null, 2)};`,
    `export declare const familyVaultFactoryAbi: readonly ${JSON.stringify(familyVaultFactoryAbi, null, 2)};`,
    `export declare const childAccountAbi: readonly ${JSON.stringify(childAccountAbi, null, 2)};`,
    `export declare const childAccountFactoryAbi: readonly ${JSON.stringify(childAccountFactoryAbi, null, 2)};`,
    `export declare const protocolEventsAbi: readonly ${JSON.stringify(protocolEventsAbi, null, 2)};`,
    "",
  ].join("\n"),
);
